services:
  - type: web
    name: blog_clone
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate &&
      python create_super_user.py &&
      gunicorn mysite.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: my_blog

      - key: DJANGO_SUPERUSER_USERNAME
        value: sid
      - key: DJANGO_SUPERUSER_EMAIL
        value: sd60rox@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: redhat