# Generated by Django 5.2.4 on 2025-07-18 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_created_date_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 4, 15, 6, 449248, tzinfo=datetime.timezone.utc)),
        ),
    ]
