# Generated by Django 5.2.4 on 2025-07-18 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 5, 27, 12, 299445, tzinfo=datetime.timezone.utc)),
        ),
    ]
